image: 'node:10.14'

stages:
  - setup
  - test
  - build
  - release

# We can't include the release job (https://git.brickblock.sh/devops/project-templates/raw/master/gitlab-ci/release.yml)
# because it is tailored to our GitLab-hosted infrastructure. This overwrite solves the release with a GitHub project.
release:
  stage: release
  extends:
    - .except-ci-release
    - .cache-pull-only
  only:
    - master
  dependencies:
    - build_npm_package
  script:
    - git config --global user.name "${GIT_USER_NAME}"
    - git config --global user.email "${GIT_USER_EMAIL}"
    - git config --global push.default current
    - yarn release
    - echo '//registry.npmjs.org/:_authToken=${SECRET_NPM_TOKEN}'>.npmrc
    - git push https://${GIT_USER_NAME}:${GITHUB_TOKEN}@github.com/strong-config/node.git HEAD:master --follow-tags
    - npm publish --access public
    - npx @brickblock/slack-changelog-notifier --projectName $CI_PROJECT_NAME

include:
  - 'https://git.brickblock.sh/devops/project-templates/raw/master/gitlab-ci/shared.yml'
  - 'https://git.brickblock.sh/devops/project-templates/raw/master/gitlab-ci/setup.yml'
  - 'https://git.brickblock.sh/devops/project-templates/raw/master/gitlab-ci/lint.yml'
  - 'https://git.brickblock.sh/devops/project-templates/raw/master/gitlab-ci/test.yml'
  - 'https://git.brickblock.sh/devops/project-templates/raw/master/gitlab-ci/build-npm-package.yml'
